spring.application.name=aiviva

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/aiviva_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL Init
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Server
server.port=8080

# Security (placeholder)
spring.security.user.name=admin
spring.security.user.password=admin123
